CREATE TABLE "EXAM" ( 
"EXAMID" VARCHAR2(10),
"LANGUAGE" VARCHAR2(10) CONSTRAINT "EXAM_LAN_NN" NOT NULL ENABLE,
"TOTAL_QUESTION" NUMBER(4,0) CONSTRAINT "EXAM_TQ_NN" NOT NULL ENABLE, 
CONSTRAINT "EXAM_EID_PK" PRIMARY KEY ("EXAMID") ENABLE ) ;


CREATE TABLE "PERFORMANCE" ( 
"USERID" VARCHAR2(10),
"EXAMID" VARCHAR2(10),
"RIGHT" NUMBER(4,0),
"WRONG" NUMBER(4,0),
"UNATTEMPTED" NUMBER(5,0),
"PER" NUMBER(5,2),
"LANGUAGE" VARCHAR2(10) );

CREATE TABLE "QUESTIONS" ( 
"EXAMID" VARCHAR2(10),
"QNO" NUMBER(5,0),
"QUESTION" VARCHAR2(100),
"ANSWER1" VARCHAR2(30),
"ANSWER2" VARCHAR2(30),
"ANSWER3" VARCHAR2(30),
"ANSWER4" VARCHAR2(30),
"CORRECT_ANSWER" VARCHAR2(10),
"LANGUAGE" VARCHAR2(10) );

CREATE TABLE "USERS" ( 
"USERID" VARCHAR2(10),
"PASSWORD" VARCHAR2(10) CONSTRAINT "USERS_PWD_NN" NOT NULL ENABLE,
"USERTYPE" VARCHAR2(10) CONSTRAINT "USERS_UTYPE_NN" NOT NULL ENABLE, 
CONSTRAINT "USERS_UID_PK" PRIMARY KEY ("USERID") ENABLE );



